#  cd into the demoProject folder
#  composer install/update --ignore-platform-reqs && php artisan key:generate
#  run docker-compose up -d --build
#  run docker-compose exec app bash php artisan migrate:fresh
#  npm install
#  npm run build
#  npm run dev

version: '3'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - app
    container_name: nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 5173:5173 # Vite port
    depends_on:
      - db
    container_name: app

  supervisor:
    build:
      context: .
      dockerfile: _docker/app/supervisor/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - app
    container_name: supervisor
    # command: supervisord -c /etc/supervisor/supervisord.conf

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: projectFilms
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
